-- poleprint DB schema for MariaDB
-- 원본 Access MDB 스키마를 MariaDB용으로 변환

CREATE TABLE IF NOT EXISTS main_table (
  id INT PRIMARY KEY,
  date DATE DEFAULT '2007-01-01',
  client_name VARCHAR(50) DEFAULT '',
  remarks VARCHAR(50) DEFAULT '',
  total_qty INT DEFAULT 0,
  unit_price INT DEFAULT 0,
  amount INT DEFAULT 0,
  pole_type INT DEFAULT 0,
  constructor VARCHAR(40) DEFAULT '',
  website VARCHAR(70) DEFAULT '',
  mgmt VARCHAR(50) DEFAULT '',
  mgmt1 VARCHAR(50) DEFAULT '',
  mgmt2 VARCHAR(50) DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS detail_jju (
  rowid INT AUTO_INCREMENT PRIMARY KEY,
  management_id INT,
  number INT DEFAULT 0,
  old_mgmt_district VARCHAR(50) DEFAULT '',
  old_computer_number VARCHAR(50) DEFAULT '',
  mgmt_district VARCHAR(50) DEFAULT '',
  pole_number VARCHAR(50) DEFAULT '',
  line_name VARCHAR(50) DEFAULT '',
  number1 VARCHAR(50) DEFAULT '',
  number2 VARCHAR(50) DEFAULT '',
  number3 VARCHAR(50) DEFAULT '',
  number4 VARCHAR(50) DEFAULT '',
  number5 VARCHAR(50) DEFAULT '',
  inspection_date VARCHAR(50) DEFAULT '',
  length VARCHAR(50) DEFAULT '',
  construction_date VARCHAR(50) DEFAULT '',
  constructor VARCHAR(50) DEFAULT '',
  dl_name VARCHAR(50) DEFAULT '',
  remark1 VARCHAR(200) DEFAULT '',
  supervisor VARCHAR(50) DEFAULT '',
  print_flag VARCHAR(10) DEFAULT '',
  entry VARCHAR(50) DEFAULT '',
  ground_resistance1 VARCHAR(50) DEFAULT '',
  ground_resistance2 VARCHAR(50) DEFAULT '',
  format VARCHAR(50) DEFAULT '',
  is_new VARCHAR(10) DEFAULT '',
  is_demolished VARCHAR(10) DEFAULT '',
  image_file VARCHAR(200) DEFAULT '',
  intake VARCHAR(50) DEFAULT '',
  sort_order INT DEFAULT 0,
  old_line_name VARCHAR(50) DEFAULT '',
  old_pole_number VARCHAR(50) DEFAULT '',
  image_path VARCHAR(200) DEFAULT '',
  output VARCHAR(10) DEFAULT '',
  current_pole_number VARCHAR(50) DEFAULT '',
  text1 VARCHAR(100) DEFAULT '',
  text2 VARCHAR(100) DEFAULT '',
  image TEXT,
  cos_fuse_capacity VARCHAR(50) DEFAULT '',
  top_label_row1 VARCHAR(100) DEFAULT '',
  top_label_row2 VARCHAR(100) DEFAULT '',
  FOREIGN KEY (management_id) REFERENCES main_table(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS detail_jjung (
  rowid INT AUTO_INCREMENT PRIMARY KEY,
  management_id INT,
  number INT DEFAULT 0,
  old_mgmt_district VARCHAR(50) DEFAULT '',
  old_computer_number VARCHAR(50) DEFAULT '',
  mgmt_district VARCHAR(50) DEFAULT '',
  pole_number VARCHAR(50) DEFAULT '',
  line_name VARCHAR(50) DEFAULT '',
  number1 VARCHAR(50) DEFAULT '',
  number2 VARCHAR(50) DEFAULT '',
  number3 VARCHAR(50) DEFAULT '',
  number4 VARCHAR(50) DEFAULT '',
  number5 VARCHAR(50) DEFAULT '',
  inspection_date VARCHAR(50) DEFAULT '',
  length VARCHAR(50) DEFAULT '',
  construction_date VARCHAR(50) DEFAULT '',
  constructor VARCHAR(50) DEFAULT '',
  dl_name VARCHAR(50) DEFAULT '',
  remark1 VARCHAR(200) DEFAULT '',
  supervisor VARCHAR(50) DEFAULT '',
  print_flag VARCHAR(10) DEFAULT '',
  entry VARCHAR(50) DEFAULT '',
  ground_resistance1 VARCHAR(50) DEFAULT '',
  ground_resistance2 VARCHAR(50) DEFAULT '',
  format VARCHAR(50) DEFAULT '',
  is_new VARCHAR(10) DEFAULT '',
  is_demolished VARCHAR(10) DEFAULT '',
  image_file VARCHAR(200) DEFAULT '',
  intake VARCHAR(50) DEFAULT '',
  sort_order INT DEFAULT 0,
  old_line_name VARCHAR(50) DEFAULT '',
  old_pole_number VARCHAR(50) DEFAULT '',
  image_path VARCHAR(200) DEFAULT '',
  output VARCHAR(10) DEFAULT '',
  current_pole_number VARCHAR(50) DEFAULT '',
  text1 VARCHAR(100) DEFAULT '',
  text2 VARCHAR(100) DEFAULT '',
  FOREIGN KEY (management_id) REFERENCES main_table(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS detail_etc (
  rowid INT AUTO_INCREMENT PRIMARY KEY,
  management_id INT,
  number INT DEFAULT 0,
  mgmt_district VARCHAR(50) DEFAULT '',
  pole_number VARCHAR(50) DEFAULT '',
  line_name VARCHAR(50) DEFAULT '',
  number1 VARCHAR(50) DEFAULT '',
  number2 VARCHAR(50) DEFAULT '',
  number3 VARCHAR(50) DEFAULT '',
  number4 VARCHAR(50) DEFAULT '',
  number5 VARCHAR(50) DEFAULT '',
  remark1 VARCHAR(200) DEFAULT '',
  remark2 VARCHAR(200) DEFAULT '',
  remark3 VARCHAR(200) DEFAULT '',
  remark4 VARCHAR(200) DEFAULT '',
  manager VARCHAR(50) DEFAULT '',
  sort_order INT DEFAULT 0,
  output VARCHAR(10) DEFAULT '',
  FOREIGN KEY (management_id) REFERENCES main_table(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS detail_kiki (
  rowid INT AUTO_INCREMENT PRIMARY KEY,
  management_id INT,
  number INT DEFAULT 0,
  mgmt_district VARCHAR(50) DEFAULT '',
  pole_number VARCHAR(50) DEFAULT '',
  line_name VARCHAR(50) DEFAULT '',
  number1 VARCHAR(50) DEFAULT '',
  number2 VARCHAR(50) DEFAULT '',
  number3 VARCHAR(50) DEFAULT '',
  number4 VARCHAR(50) DEFAULT '',
  number5 VARCHAR(50) DEFAULT '',
  line11 VARCHAR(50) DEFAULT '',
  line12 VARCHAR(50) DEFAULT '',
  line13 VARCHAR(50) DEFAULT '',
  line14 VARCHAR(50) DEFAULT '',
  line15 VARCHAR(50) DEFAULT '',
  line21 VARCHAR(50) DEFAULT '',
  line22 VARCHAR(50) DEFAULT '',
  line23 VARCHAR(50) DEFAULT '',
  line24 VARCHAR(50) DEFAULT '',
  line25 VARCHAR(50) DEFAULT '',
  line31 VARCHAR(50) DEFAULT '',
  line32 VARCHAR(50) DEFAULT '',
  line33 VARCHAR(50) DEFAULT '',
  line34 VARCHAR(50) DEFAULT '',
  line35 VARCHAR(50) DEFAULT '',
  line36 VARCHAR(50) DEFAULT '',
  print_flag VARCHAR(10) DEFAULT '',
  large_spec VARCHAR(50) DEFAULT '',
  sort_order INT DEFAULT 0,
  remark1 VARCHAR(200) DEFAULT '',
  remark2 VARCHAR(200) DEFAULT '',
  remark3 VARCHAR(200) DEFAULT '',
  remark4 VARCHAR(200) DEFAULT '',
  remark5 VARCHAR(200) DEFAULT '',
  remark6 VARCHAR(200) DEFAULT '',
  FOREIGN KEY (management_id) REFERENCES main_table(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS detail_deung (
  rowid INT AUTO_INCREMENT PRIMARY KEY,
  management_id INT,
  number INT DEFAULT 0,
  mgmt_number1 VARCHAR(50) DEFAULT '',
  mgmt_number2 VARCHAR(50) DEFAULT '',
  mgmt_number3 VARCHAR(50) DEFAULT '',
  branch_name VARCHAR(50) DEFAULT '',
  customer_number1 VARCHAR(50) DEFAULT '',
  customer_number2 VARCHAR(50) DEFAULT '',
  customer_number3 VARCHAR(50) DEFAULT '',
  computer_number1 VARCHAR(50) DEFAULT '',
  computer_number2 VARCHAR(50) DEFAULT '',
  line_name VARCHAR(50) DEFAULT '',
  pole_number1 VARCHAR(50) DEFAULT '',
  pole_number2 VARCHAR(50) DEFAULT '',
  pole_number3 VARCHAR(50) DEFAULT '',
  sort_order INT DEFAULT 0,
  output VARCHAR(10) DEFAULT '',
  FOREIGN KEY (management_id) REFERENCES main_table(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS detail_karo (
  rowid INT AUTO_INCREMENT PRIMARY KEY,
  management_id INT,
  number INT DEFAULT 0,
  area_name VARCHAR(50) DEFAULT '',
  mgmt_number1 VARCHAR(50) DEFAULT '',
  mgmt_number2 VARCHAR(50) DEFAULT '',
  phone_number1 VARCHAR(50) DEFAULT '',
  phone_number2 VARCHAR(50) DEFAULT '',
  sort_order INT DEFAULT 0,
  output VARCHAR(10) DEFAULT '',
  text1 VARCHAR(100) DEFAULT '',
  text2 VARCHAR(100) DEFAULT '',
  FOREIGN KEY (management_id) REFERENCES main_table(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS detail_cable (
  rowid INT AUTO_INCREMENT PRIMARY KEY,
  management_id INT,
  number INT DEFAULT 0,
  ha_ss VARCHAR(50) DEFAULT '',
  ha_dl VARCHAR(50) DEFAULT '',
  ha_section VARCHAR(50) DEFAULT '',
  hb_ss VARCHAR(50) DEFAULT '',
  hb_dl VARCHAR(50) DEFAULT '',
  hb_section VARCHAR(50) DEFAULT '',
  s0_number VARCHAR(50) DEFAULT '',
  s0_sw_name VARCHAR(50) DEFAULT '',
  s0_location VARCHAR(50) DEFAULT '',
  s0_ss VARCHAR(50) DEFAULT '',
  s0_dl VARCHAR(50) DEFAULT '',
  s1_number VARCHAR(50) DEFAULT '',
  s1_sw_name VARCHAR(50) DEFAULT '',
  s1_location VARCHAR(50) DEFAULT '',
  s1_ss VARCHAR(50) DEFAULT '',
  s1_dl VARCHAR(50) DEFAULT '',
  s2_number VARCHAR(50) DEFAULT '',
  s2_sw_name VARCHAR(50) DEFAULT '',
  s2_location VARCHAR(50) DEFAULT '',
  s2_ss VARCHAR(50) DEFAULT '',
  s2_dl VARCHAR(50) DEFAULT '',
  s3_number VARCHAR(50) DEFAULT '',
  s3_sw_name VARCHAR(50) DEFAULT '',
  s3_location VARCHAR(50) DEFAULT '',
  s3_ss VARCHAR(50) DEFAULT '',
  s3_dl VARCHAR(50) DEFAULT '',
  s4_number VARCHAR(50) DEFAULT '',
  s4_sw_name VARCHAR(50) DEFAULT '',
  s4_location VARCHAR(50) DEFAULT '',
  s4_ss VARCHAR(50) DEFAULT '',
  s4_dl VARCHAR(50) DEFAULT '',
  construction_date VARCHAR(50) DEFAULT '',
  construction_company VARCHAR(50) DEFAULT '',
  project_number VARCHAR(50) DEFAULT '',
  supervisor VARCHAR(50) DEFAULT '',
  remark1 VARCHAR(200) DEFAULT '',
  remark2 VARCHAR(200) DEFAULT '',
  remark3 VARCHAR(200) DEFAULT '',
  remark4 VARCHAR(200) DEFAULT '',
  remark5 VARCHAR(200) DEFAULT '',
  remark6 VARCHAR(200) DEFAULT '',
  sort_order INT DEFAULT 0,
  output VARCHAR(10) DEFAULT '',
  FOREIGN KEY (management_id) REFERENCES main_table(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS detail_cable2 (
  rowid INT AUTO_INCREMENT PRIMARY KEY,
  management_id INT,
  number INT DEFAULT 0,
  ha_ss VARCHAR(50) DEFAULT '',
  ha_dl VARCHAR(50) DEFAULT '',
  ha_section VARCHAR(50) DEFAULT '',
  hb_ss VARCHAR(50) DEFAULT '',
  hb_dl VARCHAR(50) DEFAULT '',
  hb_section VARCHAR(50) DEFAULT '',
  s0_number VARCHAR(50) DEFAULT '',
  s0_sw_name VARCHAR(50) DEFAULT '',
  s0_location VARCHAR(50) DEFAULT '',
  s0_ss VARCHAR(50) DEFAULT '',
  s0_dl VARCHAR(50) DEFAULT '',
  s1_number VARCHAR(50) DEFAULT '',
  s1_sw_name VARCHAR(50) DEFAULT '',
  s1_location VARCHAR(50) DEFAULT '',
  s1_ss VARCHAR(50) DEFAULT '',
  s1_dl VARCHAR(50) DEFAULT '',
  s2_number VARCHAR(50) DEFAULT '',
  s2_sw_name VARCHAR(50) DEFAULT '',
  s2_location VARCHAR(50) DEFAULT '',
  s2_ss VARCHAR(50) DEFAULT '',
  s2_dl VARCHAR(50) DEFAULT '',
  s3_number VARCHAR(50) DEFAULT '',
  s3_sw_name VARCHAR(50) DEFAULT '',
  s3_location VARCHAR(50) DEFAULT '',
  s3_ss VARCHAR(50) DEFAULT '',
  s3_dl VARCHAR(50) DEFAULT '',
  s4_number VARCHAR(50) DEFAULT '',
  s4_sw_name VARCHAR(50) DEFAULT '',
  s4_location VARCHAR(50) DEFAULT '',
  s4_ss VARCHAR(50) DEFAULT '',
  s4_dl VARCHAR(50) DEFAULT '',
  construction_date VARCHAR(50) DEFAULT '',
  construction_company VARCHAR(50) DEFAULT '',
  project_number VARCHAR(50) DEFAULT '',
  supervisor VARCHAR(50) DEFAULT '',
  remark1 VARCHAR(200) DEFAULT '',
  remark2 VARCHAR(200) DEFAULT '',
  remark3 VARCHAR(200) DEFAULT '',
  remark4 VARCHAR(200) DEFAULT '',
  remark5 VARCHAR(200) DEFAULT '',
  remark6 VARCHAR(200) DEFAULT '',
  sort_order INT DEFAULT 0,
  output VARCHAR(10) DEFAULT '',
  FOREIGN KEY (management_id) REFERENCES main_table(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS detail_cable_label (
  rowid INT AUTO_INCREMENT PRIMARY KEY,
  management_id INT,
  number INT DEFAULT 0,
  ha_ss VARCHAR(50) DEFAULT '',
  ha_dl VARCHAR(50) DEFAULT '',
  ha_section VARCHAR(50) DEFAULT '',
  hb_ss VARCHAR(50) DEFAULT '',
  hb_dl VARCHAR(50) DEFAULT '',
  hb_section VARCHAR(50) DEFAULT '',
  s0_number VARCHAR(50) DEFAULT '',
  s0_sw_name VARCHAR(50) DEFAULT '',
  s0_location VARCHAR(50) DEFAULT '',
  s0_ss VARCHAR(50) DEFAULT '',
  s0_dl VARCHAR(50) DEFAULT '',
  s1_number VARCHAR(50) DEFAULT '',
  s1_sw_name VARCHAR(50) DEFAULT '',
  s1_location VARCHAR(50) DEFAULT '',
  s1_ss VARCHAR(50) DEFAULT '',
  s1_dl VARCHAR(50) DEFAULT '',
  s2_number VARCHAR(50) DEFAULT '',
  s2_sw_name VARCHAR(50) DEFAULT '',
  s2_location VARCHAR(50) DEFAULT '',
  s2_ss VARCHAR(50) DEFAULT '',
  s2_dl VARCHAR(50) DEFAULT '',
  s3_number VARCHAR(50) DEFAULT '',
  s3_sw_name VARCHAR(50) DEFAULT '',
  s3_location VARCHAR(50) DEFAULT '',
  s3_ss VARCHAR(50) DEFAULT '',
  s3_dl VARCHAR(50) DEFAULT '',
  s4_number VARCHAR(50) DEFAULT '',
  s4_sw_name VARCHAR(50) DEFAULT '',
  s4_location VARCHAR(50) DEFAULT '',
  s4_ss VARCHAR(50) DEFAULT '',
  s4_dl VARCHAR(50) DEFAULT '',
  construction_date VARCHAR(50) DEFAULT '',
  construction_company VARCHAR(50) DEFAULT '',
  project_number VARCHAR(50) DEFAULT '',
  supervisor VARCHAR(50) DEFAULT '',
  remark1 VARCHAR(200) DEFAULT '',
  remark2 VARCHAR(200) DEFAULT '',
  remark3 VARCHAR(200) DEFAULT '',
  remark4 VARCHAR(200) DEFAULT '',
  remark5 VARCHAR(200) DEFAULT '',
  remark6 VARCHAR(200) DEFAULT '',
  sort_order INT DEFAULT 0,
  output VARCHAR(10) DEFAULT '',
  FOREIGN KEY (management_id) REFERENCES main_table(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- DB version tracking
CREATE TABLE IF NOT EXISTS db_info (
  version INT DEFAULT 1
);

INSERT INTO db_info (version) SELECT 1 WHERE NOT EXISTS (SELECT 1 FROM db_info);
